version: '3.8'
services:
  db:
    image: mysql:8.4.2
    environment:
      MYSQL_ROOT_PASSWORD: "@October4th2018"
      MYSQL_DATABASE: "youtube_videos"
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    build: .
    environment:
      MYSQL_CONN: "root:@October4th2018@tcp(db:3306)/youtube_videos"
      DB_HOST: "db"
      DB_PORT: "3306"
      DB_USER: "root"
      DB_PASSWORD: "@October4th2018"
      DB_NAME: "youtube_videos"
      API_KEY: "AIzaSyBhrDtIxAOBKHKRquclq0j6c3XUEdhr2QQ"
      FETCH_INTERVAL: "10"
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  db_data:
